"""Add column price

Revision ID: 506cf1588def
Revises: 908530dcb166
Create Date: 2021-07-09 14:03:44.310681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '506cf1588def'
down_revision = '908530dcb166'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_details', sa.Column('price', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_details', 'price')
    # ### end Alembic commands ###
