"""Restore some columns

Revision ID: 908530dcb166
Revises: d88bf9ac6f99
Create Date: 2021-07-07 23:39:49.514426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '908530dcb166'
down_revision = 'd88bf9ac6f99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_details', sa.Column('product_images', sa.JSON(), nullable=True))
    op.add_column('product_details', sa.Column('product_category', sa.JSON(), nullable=True))
    op.add_column('product_details', sa.Column('seller', sa.JSON(), nullable=True))
    op.add_column('product_details', sa.Column('seller_details', sa.JSON(), nullable=True))
    op.add_column('product_details', sa.Column('price_summary', sa.JSON(), nullable=True))
    op.add_column('product_details', sa.Column('attributes', sa.JSON(), nullable=True))
    op.add_column('product_details', sa.Column('reviews_ratings', sa.JSON(), nullable=True))
    op.add_column('product_details', sa.Column('properties', sa.JSON(), nullable=True))
    op.add_column('product_details', sa.Column('variations', sa.JSON(), nullable=True))
    op.add_column('product_details', sa.Column('shipping', sa.JSON(), nullable=True))
    op.drop_index('ix_product_details_has_attributes', table_name='product_details')
    op.drop_index('ix_product_details_has_reviews_ratings', table_name='product_details')
    op.drop_index('ix_product_details_has_single_price', table_name='product_details')
    op.drop_index('ix_product_details_locale', table_name='product_details')
    op.drop_index('ix_product_details_product_url', table_name='product_details')
    op.drop_index('ix_product_details_status', table_name='product_details')
    op.drop_index('ix_product_details_status_id', table_name='product_details')
    op.drop_index('ix_product_details_title', table_name='product_details')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_product_details_title', 'product_details', ['title'], unique=False)
    op.create_index('ix_product_details_status_id', 'product_details', ['status_id'], unique=False)
    op.create_index('ix_product_details_status', 'product_details', ['status'], unique=False)
    op.create_index('ix_product_details_product_url', 'product_details', ['product_url'], unique=False)
    op.create_index('ix_product_details_locale', 'product_details', ['locale'], unique=False)
    op.create_index('ix_product_details_has_single_price', 'product_details', ['has_single_price'], unique=False)
    op.create_index('ix_product_details_has_reviews_ratings', 'product_details', ['has_reviews_ratings'], unique=False)
    op.create_index('ix_product_details_has_attributes', 'product_details', ['has_attributes'], unique=False)
    op.drop_column('product_details', 'shipping')
    op.drop_column('product_details', 'variations')
    op.drop_column('product_details', 'properties')
    op.drop_column('product_details', 'reviews_ratings')
    op.drop_column('product_details', 'attributes')
    op.drop_column('product_details', 'price_summary')
    op.drop_column('product_details', 'seller_details')
    op.drop_column('product_details', 'seller')
    op.drop_column('product_details', 'product_category')
    op.drop_column('product_details', 'product_images')
    # ### end Alembic commands ###
