"""Create users table

Revision ID: a6f78acbd1c0
Revises: 1c1cf1730b14
Create Date: 2021-07-20 01:10:58.789896

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "a6f78acbd1c0"
down_revision = "1c1cf1730b14"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "create_dt",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("update_dt", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("user_id", sa.String(length=100)),
        sa.Column("email", sa.String(length=120)),
        sa.Column("hashed_password", sa.String(length=200)),
        sa.Column("first_name", sa.String(length=30)),
        sa.Column("last_name", sa.String(length=30)),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_user_id"), "users", ["user_id"], unique=False)
    op.create_unique_constraint("uq_users_user_id", "users", ["user_id"])
    op.create_unique_constraint("uq_users_email", "users", ["email"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_user_id"), table_name="users")
    op.drop_constraint("uq_users_user_id", "user_id", type_="unique")
    op.drop_constraint("uq_users_email", "email", type_="unique")
    op.drop_table("users")
    # ### end Alembic commands ###
