"""Fixed hashed_password column and rename to password

Revision ID: e3662d962406
Revises: 9da9ef9e0ad5
Create Date: 2021-07-28 00:43:31.016334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e3662d962406"
down_revision = "9da9ef9e0ad5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("password", sa.String(length=60), nullable=False))
    op.drop_column("users", "hashed_password")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("hashed_password", sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    )
    op.drop_column("users", "password")
    # ### end Alembic commands ###
