"""Changed from product to information in product_list

Revision ID: 005a8708d74d
Revises: d7fb708c25b2
Create Date: 2021-07-03 17:33:38.064234

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '005a8708d74d'
down_revision = 'd7fb708c25b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_lists', sa.Column('information', sa.JSON(), nullable=True))
    op.drop_column('product_lists', 'product')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_lists', sa.Column('product', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('product_lists', 'information')
    # ### end Alembic commands ###
