"""first migration

Revision ID: d6d6cb7eee1d
Revises: 
Create Date: 2021-07-03 16:11:17.979257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6d6cb7eee1d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('productUrl', sa.String(), nullable=True),
    sa.Column('productId', sa.String(), nullable=True),
    sa.Column('statusId', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('locale', sa.String(), nullable=True),
    sa.Column('shipTo', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('totalStock', sa.Integer(), nullable=True),
    sa.Column('totalOrders', sa.Integer(), nullable=True),
    sa.Column('wishlistCount', sa.Integer(), nullable=True),
    sa.Column('unitName', sa.String(), nullable=True),
    sa.Column('unitNamePlural', sa.String(), nullable=True),
    sa.Column('unitsPerProduct', sa.Integer(), nullable=True),
    sa.Column('hasPurchaseLimit', sa.Boolean(), nullable=True),
    sa.Column('maxPurchaseLimit', sa.Integer(), nullable=True),
    sa.Column('processingTimeInDays', sa.Integer(), nullable=True),
    sa.Column('productImages', sa.String(), nullable=True),
    sa.Column('productCategory', sa.String(), nullable=True),
    sa.Column('seller', sa.String(), nullable=True),
    sa.Column('sellerDetails', sa.String(), nullable=True),
    sa.Column('hasSinglePrice', sa.Boolean(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('hasAttributes', sa.Boolean(), nullable=True),
    sa.Column('attributes', sa.String(), nullable=True),
    sa.Column('hasReviewsRatings', sa.Boolean(), nullable=True),
    sa.Column('reviewsRatings', sa.String(), nullable=True),
    sa.Column('hasProperties', sa.Boolean(), nullable=True),
    sa.Column('properties', sa.String(), nullable=True),
    sa.Column('hasVariations', sa.Boolean(), nullable=True),
    sa.Column('variations', sa.String(), nullable=True),
    sa.Column('shipping', sa.String(), nullable=True),
    sa.Column('htmlDescription', sa.String(), nullable=True),
    sa.Column('priceSummary', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_details_attributes'), 'product_details', ['attributes'], unique=False)
    op.create_index(op.f('ix_product_details_currency'), 'product_details', ['currency'], unique=False)
    op.create_index(op.f('ix_product_details_hasAttributes'), 'product_details', ['hasAttributes'], unique=False)
    op.create_index(op.f('ix_product_details_hasProperties'), 'product_details', ['hasProperties'], unique=False)
    op.create_index(op.f('ix_product_details_hasPurchaseLimit'), 'product_details', ['hasPurchaseLimit'], unique=False)
    op.create_index(op.f('ix_product_details_hasReviewsRatings'), 'product_details', ['hasReviewsRatings'], unique=False)
    op.create_index(op.f('ix_product_details_hasSinglePrice'), 'product_details', ['hasSinglePrice'], unique=False)
    op.create_index(op.f('ix_product_details_hasVariations'), 'product_details', ['hasVariations'], unique=False)
    op.create_index(op.f('ix_product_details_htmlDescription'), 'product_details', ['htmlDescription'], unique=False)
    op.create_index(op.f('ix_product_details_id'), 'product_details', ['id'], unique=False)
    op.create_index(op.f('ix_product_details_locale'), 'product_details', ['locale'], unique=False)
    op.create_index(op.f('ix_product_details_maxPurchaseLimit'), 'product_details', ['maxPurchaseLimit'], unique=False)
    op.create_index(op.f('ix_product_details_price'), 'product_details', ['price'], unique=False)
    op.create_index(op.f('ix_product_details_priceSummary'), 'product_details', ['priceSummary'], unique=False)
    op.create_index(op.f('ix_product_details_processingTimeInDays'), 'product_details', ['processingTimeInDays'], unique=False)
    op.create_index(op.f('ix_product_details_productCategory'), 'product_details', ['productCategory'], unique=False)
    op.create_index(op.f('ix_product_details_productId'), 'product_details', ['productId'], unique=False)
    op.create_index(op.f('ix_product_details_productImages'), 'product_details', ['productImages'], unique=False)
    op.create_index(op.f('ix_product_details_productUrl'), 'product_details', ['productUrl'], unique=False)
    op.create_index(op.f('ix_product_details_properties'), 'product_details', ['properties'], unique=False)
    op.create_index(op.f('ix_product_details_reviewsRatings'), 'product_details', ['reviewsRatings'], unique=False)
    op.create_index(op.f('ix_product_details_seller'), 'product_details', ['seller'], unique=False)
    op.create_index(op.f('ix_product_details_sellerDetails'), 'product_details', ['sellerDetails'], unique=False)
    op.create_index(op.f('ix_product_details_shipTo'), 'product_details', ['shipTo'], unique=False)
    op.create_index(op.f('ix_product_details_shipping'), 'product_details', ['shipping'], unique=False)
    op.create_index(op.f('ix_product_details_status'), 'product_details', ['status'], unique=False)
    op.create_index(op.f('ix_product_details_statusId'), 'product_details', ['statusId'], unique=False)
    op.create_index(op.f('ix_product_details_title'), 'product_details', ['title'], unique=False)
    op.create_index(op.f('ix_product_details_totalOrders'), 'product_details', ['totalOrders'], unique=False)
    op.create_index(op.f('ix_product_details_totalStock'), 'product_details', ['totalStock'], unique=False)
    op.create_index(op.f('ix_product_details_unitName'), 'product_details', ['unitName'], unique=False)
    op.create_index(op.f('ix_product_details_unitNamePlural'), 'product_details', ['unitNamePlural'], unique=False)
    op.create_index(op.f('ix_product_details_unitsPerProduct'), 'product_details', ['unitsPerProduct'], unique=False)
    op.create_index(op.f('ix_product_details_variations'), 'product_details', ['variations'], unique=False)
    op.create_index(op.f('ix_product_details_wishlistCount'), 'product_details', ['wishlistCount'], unique=False)
    op.create_table('search_texts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_texts_id'), 'search_texts', ['id'], unique=False)
    op.create_index(op.f('ix_search_texts_text'), 'search_texts', ['text'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_description'), 'items', ['description'], unique=False)
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_index(op.f('ix_items_title'), 'items', ['title'], unique=False)
    op.create_table('product_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product', sa.JSON(), nullable=True),
    sa.Column('search_text_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['search_text_id'], ['search_texts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_lists_id'), 'product_lists', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_lists_id'), table_name='product_lists')
    op.drop_table('product_lists')
    op.drop_index(op.f('ix_items_title'), table_name='items')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_index(op.f('ix_items_description'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_search_texts_text'), table_name='search_texts')
    op.drop_index(op.f('ix_search_texts_id'), table_name='search_texts')
    op.drop_table('search_texts')
    op.drop_index(op.f('ix_product_details_wishlistCount'), table_name='product_details')
    op.drop_index(op.f('ix_product_details_variations'), table_name='product_details')
    op.drop_index(op.f('ix_product_details_unitsPerProduct'), table_name='product_details')
    op.drop_index(op.f('ix_product_details_unitNamePlural'), table_name='product_details')
    op.drop_index(op.f('ix_product_details_unitName'), table_name='product_details')
    op.drop_index(op.f('ix_product_details_totalStock'), table_name='product_details')
    op.drop_index(op.f('ix_product_details_totalOrders'), table_name='product_details')
    op.drop_index(op.f('ix_product_details_title'), table_name='product_details')
    op.drop_index(op.f('ix_product_details_statusId'), table_name='product_details')
    op.drop_index(op.f('ix_product_details_status'), table_name='product_details')
    op.drop_index(op.f('ix_product_details_shipping'), table_name='product_details')
    op.drop_index(op.f('ix_product_details_shipTo'), table_name='product_details')
    op.drop_index(op.f('ix_product_details_sellerDetails'), table_name='product_details')
    op.drop_index(op.f('ix_product_details_seller'), table_name='product_details')
    op.drop_index(op.f('ix_product_details_reviewsRatings'), table_name='product_details')
    op.drop_index(op.f('ix_product_details_properties'), table_name='product_details')
    op.drop_index(op.f('ix_product_details_productUrl'), table_name='product_details')
    op.drop_index(op.f('ix_product_details_productImages'), table_name='product_details')
    op.drop_index(op.f('ix_product_details_productId'), table_name='product_details')
    op.drop_index(op.f('ix_product_details_productCategory'), table_name='product_details')
    op.drop_index(op.f('ix_product_details_processingTimeInDays'), table_name='product_details')
    op.drop_index(op.f('ix_product_details_priceSummary'), table_name='product_details')
    op.drop_index(op.f('ix_product_details_price'), table_name='product_details')
    op.drop_index(op.f('ix_product_details_maxPurchaseLimit'), table_name='product_details')
    op.drop_index(op.f('ix_product_details_locale'), table_name='product_details')
    op.drop_index(op.f('ix_product_details_id'), table_name='product_details')
    op.drop_index(op.f('ix_product_details_htmlDescription'), table_name='product_details')
    op.drop_index(op.f('ix_product_details_hasVariations'), table_name='product_details')
    op.drop_index(op.f('ix_product_details_hasSinglePrice'), table_name='product_details')
    op.drop_index(op.f('ix_product_details_hasReviewsRatings'), table_name='product_details')
    op.drop_index(op.f('ix_product_details_hasPurchaseLimit'), table_name='product_details')
    op.drop_index(op.f('ix_product_details_hasProperties'), table_name='product_details')
    op.drop_index(op.f('ix_product_details_hasAttributes'), table_name='product_details')
    op.drop_index(op.f('ix_product_details_currency'), table_name='product_details')
    op.drop_index(op.f('ix_product_details_attributes'), table_name='product_details')
    op.drop_table('product_details')
    # ### end Alembic commands ###
