"""added create_dt update_dt fields

Revision ID: d7fb708c25b2
Revises: d6d6cb7eee1d
Create Date: 2021-07-03 16:34:40.807677

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d7fb708c25b2"
down_revision = "d6d6cb7eee1d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product_lists",
        sa.Column(
            "create_dt",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    op.add_column(
        "product_lists", sa.Column("update_dt", postgresql.TIMESTAMP(timezone=True), nullable=True)
    )
    op.drop_index("ix_product_lists_id", table_name="product_lists")
    op.add_column(
        "search_texts",
        sa.Column(
            "create_dt",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    op.add_column(
        "search_texts", sa.Column("update_dt", postgresql.TIMESTAMP(timezone=True), nullable=True)
    )
    op.drop_index("ix_search_texts_id", table_name="search_texts")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_search_texts_id", "search_texts", ["id"], unique=False)
    op.drop_column("search_texts", "update_dt")
    op.drop_column("search_texts", "create_dt")
    op.create_index("ix_product_lists_id", "product_lists", ["id"], unique=False)
    op.drop_column("product_lists", "update_dt")
    op.drop_column("product_lists", "create_dt")
    # ### end Alembic commands ###
