"""Dropped user_id column and email column

Revision ID: e833149c7595
Revises: a6f78acbd1c0
Create Date: 2021-07-27 18:07:43.312987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e833149c7595'
down_revision = 'a6f78acbd1c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_user_id', table_name='users')
    op.drop_constraint('uq_users_email', 'users', type_='unique')
    op.drop_constraint('uq_users_user_id', 'users', type_='unique')
    op.drop_column('users', 'user_id')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('user_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_unique_constraint('uq_users_user_id', 'users', ['user_id'])
    op.create_unique_constraint('uq_users_email', 'users', ['email'])
    op.create_index('ix_users_user_id', 'users', ['user_id'], unique=False)
    # ### end Alembic commands ###
